"""ETF universe groups supplied by the user for scanning, portfolios and backtests.

The symbol lists below are transcribed from the uploaded CSV bundle (2026-10-10).
"""

from __future__ import annotations

import pandas as pd

_RAW_GROUPS = {
    'ALL ETF': """
        ABGSEC ABSL10BANK ABSLBANETF ABSLLIQUID ABSLMSCIN ABSLNN50ET ABSLPSE ALPHA ALPHAETF ALPL30IETF AONEGOLD AONELIQUID
        AONENIFTY AONESILVER AONETMMQ50 AONETOTAL AUTOBEES AUTOIETF BANK10ADD BANK10BETF BANKADD BANKBEES BANKBETA BANKBETF
        BANKETF BANKIETF BANKNIFTY1 BANKPSU BBETF0432 BBNPNBETF BBNPPGOLD BFSI BNKETFAXIS BSE500IETF BSLGOLDETF BSLNIFTY
        BSLSENETFG CASHIETF CEMNTGROWW CHEMICAL CHOICEGOLD COMMOIETF CONS CONSUMAXIS CONSUMBEES CONSUMER CONSUMIETF CPSEETF
        DEFENCE DIVIDEND DIVOPPBEES EBANK10 EBANKNIFTY EBBETF0430 EBBETF0431 EBBETF0433 ECAPINSURE EGOLD ELIQUID ELM250
        ELMDIV EMETAL EMULTIMQ ENERGY ENERGYAXIS ENEXT50 ENIFTY EQUAL200 EQUAL50 EQUAL50ADD ESENSEX ESG
        ESILVER EVIETF EVINDIA FINIETF FLEXIADD FMCGADD FMCGIETF GILT10BETA GILT5BETA GILT5YBEES GOLD1 GOLD360
        GOLDADD GOLDAXIS GOLDBEES GOLDBETA GOLDBND GOLDCASE GOLDETF GOLDIETF GROWWCAPM GROWWCHEM GROWWDEFNC GROWWEV
        GROWWGOLD GROWWHOSPI GROWWLIQID GROWWLOVOL GROWWMC150 GROWWMETAL GROWWMOM50 GROWWN200 GROWWNET GROWWNIFTY GROWWNXT50 GROWWPOWER
        GROWWPSE GROWWPSUBK GROWWRAIL GROWWRLTY GROWWSC250 GROWWSLVR GSEC10ABSL GSEC10ADD GSEC10IETF GSEC10YEAR GSEC5IETF HDFCBSE500
        HDFCGOLD HDFCGROWTH HDFCLIQUID HDFCLOWVOL HDFCMID150 HDFCMOMENT HDFCNEXT50 HDFCNIF100 HDFCNIFBAN HDFCNIFIT HDFCNIFTY HDFCNIMEG
        HDFCPSUBK HDFCPVTBAN HDFCQUAL HDFCSENSEX HDFCSILVER HDFCSML250 HDFCVALUE HEALTHADD HEALTHAXIS HEALTHCARE HEALTHIETF HEALTHY
        HNGSNGBEES HSBCGOLD HYBRIDETF ICICIB22 IDFNIFTYET INFRA INFRABEES INFRAIETF INSURADD INSUREIETF INTERNET IT
        ITADD ITAXIS ITBEES ITBETA ITETF ITIETF IVZBANKNF IVZINGOLD IVZINNIFTY IVZSENSEX JUNIORBEES LARGEMID50
        LICMFGOLD LICNETFGSC LICNETFN50 LICNETFSEN LICNFNHGP LICNMID100 LIQGRWBEES LIQUID LIQUID1 LIQUIDADD LIQUIDBEES LIQUIDBETA
        LIQUIDBETF LIQUIDCASE LIQUIDETF LIQUIDIETF LIQUIDPLUS LIQUIDSBI LIQUIDSHRI LOWVOL LOWVOL1 LOWVOLIETF LTGILTBEES LTGILTCASE
        MAFANG MAHKTECH MAKEINDIA MANUFGBEES MASPTOP50 METAL METALIETF MID150 MID150BEES MID150CASE MIDBANKADD MIDCAP
        MIDCAPADD MIDCAPBETA MIDCAPETF MIDCAPIETF MIDQ50ADD MIDSELIETF MIDSMALL MNC MOALPHA50 MOBANK10 MOCAPITAL MODEFENCE
        MOENERGY MOGOLD MOGSEC MOHEALTH MOINFRA MOIPO MOLOWVOL MOM100 MOM30IETF MOM50 MOMENTUM MOMENTUM30
        MOMENTUM50 MOMETAL MOMGF MOMIDMTM MOMMIDCAP MOMNC MOMOMENTUM MON100 MON50EQUAL MONEXT50 MONIFTY100 MONIFTY500
        MONQ50 MOOILGAS MOPSE MOQUALITY MOREALTY MOSERVICE MOSILVER MOSMALL250 MOTOUR MOVALUE MSCI360 MSCIADD
        MSCIINDIA MULTICAP NETF NEXT30ADD NEXT50 NEXT50ADD NEXT50BETA NEXT50ETF NEXT50IETF NIF100BEES NIF100IETF NIF500BETA
        NIFTY1 NIFTY100EW NIFTYADD NIFTYAXIS NIFTYBEES NIFTYBETA NIFTYBETF NIFTYCASE NIFTYETF NIFTYIETF NIFTYJBLK NIFTYQLITY
        NPBET NV20 NV20BEES NV20IETF OILIETF PHARMABEES PSUBANK PSUBANKADD PSUBNKBEES PSUBNKIETF PVTBANIETF PVTBANK
        PVTBANKADD PVTBKGROWW QGOLDHALF QNIFTY QUAL30IETF QUALITY30 SBIBPB SBIETFCON SBIETFIT SBIETFPB SBIETFQLTY SBILIQETF
        SBIMIDMOM SBINEQWETF SBINMID150 SBISILVER SBISMLETF SBIVALETF SECLEDBETA SELECTIPO SENSEXADD SENSEXAXIS SENSEXBETA SENSEXETF
        SENSEXIETF SETF10GILT SETFGOLD SETFNIF50 SETFNIFBK SETFNN50 SHARIABEES SILVER SILVER001 SILVER1 SILVER360 SILVERADD
        SILVERAG SILVERAXIS SILVERBEES SILVERBETA SILVERBND SILVERCASE SILVERIETF SMALL250 SMALLADD SMALLCAP SMALLGROWW SMALLIETF
        SML100CASE SNXT30BEES SNXT50BETA TATAGOLD TATSILV TECH TNIDETF TOP100CASE TOP10ADD TOP15IETF TOP20 TWCGOLDETF
        UNIONGOLD VAL30IETF VALUE VALUEAXIS
    """.split(),

    'ALL ETFs (Liquid)': """
        ABSLBANETF ALPHA ALPHAETF ALPL30IETF AONEGOLD AONENIFTY AONESILVER AONETOTAL AUTOBEES AUTOIETF BANK10ADD BANK10BETF
        BANKBEES BANKBETA BANKIETF BANKNIFTY1 BFSI BSE500IETF BSLGOLDETF BSLNIFTY CASHIETF CHEMICAL CONSUMER CPSEETF
        DEFENCE EGOLD ELM250 ENERGY ESILVER EVIETF EVINDIA FINIETF FLEXIADD FMCGIETF GILT5YBEES GOLD1
        GOLDADD GOLDAXIS GOLDBEES GOLDBETA GOLDCASE GOLDETF GOLDIETF GROWWCAPM GROWWCHEM GROWWDEFNC GROWWEV GROWWGOLD
        GROWWHOSPI GROWWMETAL GROWWMOM50 GROWWNET GROWWNIFTY GROWWPOWER GROWWRAIL GROWWRLTY GROWWSC250 GROWWSLVR HDFCBSE500 HDFCGOLD
        HDFCMID150 HDFCMOMENT HDFCNEXT50 HDFCNIFBAN HDFCNIFIT HDFCNIFTY HDFCPVTBAN HDFCSILVER HDFCSML250 HEALTHIETF HEALTHY ICICIB22
        INFRAIETF INSUREIETF INTERNET IT ITADD ITBEES ITETF ITIETF JUNIORBEES LICMFGOLD LOWVOL1 LOWVOLIETF
        LTGILTBEES LTGILTCASE MAFANG MAHKTECH MASPTOP50 METAL METALIETF MID150 MID150BEES MID150CASE MIDCAP MIDCAPETF
        MIDCAPIETF MIDSELIETF MIDSMALL MOCAPITAL MODEFENCE MOLOWVOL MOM100 MOM30IETF MOMENTUM30 MOMENTUM50 MOMMIDCAP MON100
        MONIFTY500 MONQ50 MOREALTY MOSMALL250 MULTICAP NEXT50BETA NEXT50IETF NIFTY1 NIFTYBEES NIFTYBETA NIFTYCASE NIFTYETF
        NIFTYIETF NIFTYJBLK NV20 NV20IETF OILIETF PHARMABEES PSUBANK PSUBNKBEES PVTBANIETF PVTBANKADD QGOLDHALF SBIBPB
        SBIETFPB SBISILVER SETFGOLD SETFNIF50 SILVER SILVER1 SILVERADD SILVERAG SILVERAXIS SILVERBEES SILVERBETA SILVERCASE
        SILVERIETF SMALL250 SMALLCAP SML100CASE TATAGOLD TATSILV TNIDETF TOP100CASE TOP10ADD TOP15IETF VAL30IETF
    """.split(),

    'All-One ETFs': """
        ABSLPSE ALPHA AONETOTAL AUTOBEES BANKBEES BFSI CHEMICAL COMMOIETF CONSUMBEES CONSUMER CPSEETF DIVOPPBEES
        ENERGY ESG FINIETF FMCGIETF GILT5YBEES GOLDBEES GROWWEV GROWW HOSPI GROWWPOWER GROWWRAIL HDFCGROWTH HDFCSML250
        HEALTHIETF HNGSNGBEES ICICIB22 INFRAIETF ITBEES JUNIORBEES LIQUIDCASE LOWVOLIETF LTGILTBEES MAFANG MAHKTECH MAKEINDIA
        MASPTOP50 METALIETF MID150BEES MIDSMALL MNC MOCAPITAL MODEFENCE MOM30IETF MOMENTUM50 MON100 MONQ50 MOREALTY
        MSCIINDIA MULTICAP NIFTYBEES OILIETF PHARMABEES PSUBNKBEES PVTBANIETF SELECTIPO SILVERBEES TNIDETF TOP10ADD
    """.split(),

    'All-One ETFs (Domestic)': """
        ABSLPSE ALPHA AONETOTAL AUTOBEES BANKBEES BFSI CHEMICAL COMMOIETF CONSUMBEES CONSUMER CPSEETF DIVOPPBEES
        ENERGY ESG FINIETF FMCGIETF GILT5YBEES GOLDBEES GROWWEV GROWW HOSPI GROWWPOWER GROWWRAIL HDFCGROWTH HDFCSML250
        HEALTHIETF ICICIB22 INFRAIETF ITBEES JUNIORBEES LIQUIDCASE LOWVOLIETF LTGILTBEES MAKEINDIA METALIETF MID150BEES MIDSMALL
        MNC MOCAPITAL MODEFENCE MOM30IETF MOMENTUM50 MOREALTY MSCIINDIA MULTICAP NIFTYBEES OILIETF PHARMABEES PSUBNKBEES
        PVTBANIETF SELECTIPO SILVERBEES TNIDETF TOP10ADD
    """.split(),

    'All-One Domestic ETF Assets': """
        GOLDBEES LTGILTBEES NIFTYBEES SILVERBEES
    """.split(),

    'All-One Domestic ETF Factors': """
        LOWVOLIETF MOM30IETF QUAL30IETF VAL30IETF
    """.split(),

    'All-One Domestic ETF Sectors': """
        ABSLPSE AUTOBEES BANKBEES BFSI CHEMICAL COMMOIETF CONSUMBEES CONSUMER CPSEETF ENERGY EVINDIA FINIETF
        FMCGIETF GROWWPOWER GROWWRAIL HEALTHIETF INFRAIETF ITBEES MAKEINDIA METALIETF MNC MOCAPITAL MODEFENCE MOREALTY
        OILIETF PHARMABEES PSUBNKBEES PVTBANIETF TNIDETF
    """.split(),

    'All-One Domestic ETF Segments': """
        HDFCSML250 JUNIORBEES LTGILTBEES MID150BEES MONIFTY500 NIFTYBEES
    """.split(),

    'All-Sector ETFs': """
        ABSLPSE AUTOBEES BANKBEES BFSI CHEMICAL COMMOIETF CONSUMBEES CONSUMER CPSEETF ENERGY FINIETF FMCGIETF
        GROWWEV GROWW HOSPI GROWWPOWER GROWWRAIL HEALTHIETF ICICIB22 INFRAIETF ITBEES MAKEINDIA METALIETF MNC MOCAPITAL
        MODEFENCE MOREALTY OILIETF PHARMABEES PSUBNKBEES PVTBANIETF TNIDETF
    """.split(),
}
INTERNATIONAL_EXPOSURE_SYMBOLS = {
    "HNGSNGBEES", "MAFANG", "MAHKTECH", "MASPTOP50", "MON100", "MONQ50",
}
INTERNATIONAL_LIQUID_SYMBOLS = {"MAFANG", "MAHKTECH", "MASPTOP50", "MON100", "MONQ50"}

ETF_GROUP_SYMBOLS: dict[str, list[str]] = dict(_RAW_GROUPS)
ETF_GROUP_SYMBOLS["International ETF"] = [
    symbol for symbol in ETF_GROUP_SYMBOLS["ALL ETFs (Liquid)"]
    if symbol in INTERNATIONAL_LIQUID_SYMBOLS
]
ETF_GROUP_SYMBOLS["Domestic ETF"] = [
    symbol for symbol in ETF_GROUP_SYMBOLS["ALL ETF"]
    if symbol not in INTERNATIONAL_EXPOSURE_SYMBOLS
]
_DEFENSIVE_TERMS = ("GOLD", "SILVER", "GILT", "GSEC", "LIQUID", "CASH", "BOND")
ETF_GROUP_SYMBOLS["Defensive ETF"] = [
    symbol for symbol in ETF_GROUP_SYMBOLS["ALL ETFs (Liquid)"]
    if any(term in symbol.upper() for term in _DEFENSIVE_TERMS)
]

ETF_GROUP_NAMES = list(ETF_GROUP_SYMBOLS.keys())
ETF_GROUP_ALIASES = {"All ETFs": "ALL ETF"}

def canonical_etf_group(name: str) -> str:
    return ETF_GROUP_ALIASES.get(name, name)

def get_etf_group_symbols(name: str) -> list[str]:
    """Resolve a group name to NSE-listed Yahoo Finance tickers."""
    group = canonical_etf_group(name)
    symbols = ETF_GROUP_SYMBOLS.get(group, [])
    return [f"{symbol}.NS" for symbol in symbols]

def get_etf_group_constituents(name: str) -> tuple[pd.DataFrame, str]:
    """Make the uploaded symbol-only group available in the constituent viewer."""
    group = canonical_etf_group(name)
    symbols = ETF_GROUP_SYMBOLS.get(group)
    if symbols is None:
        raise ValueError(f"Unknown ETF group: {name}")
    df = pd.DataFrame({
        "Company Name": symbols,
        "Industry": [group] * len(symbols),
        "Symbol": symbols,
        "Yahoo Ticker": [f"{symbol}.NS" for symbol in symbols],
        "Series": [""] * len(symbols),
        "ISIN Code": [""] * len(symbols),
    })
    return df, "Uploaded ETF symbol list: ETF and bees.zip"
